# commands:
helloilaris_help: "Greets the Ilaris Bot."
helloilaris_reply: "Hey, <@{author}>!"

creatures_help: "Gets link to KreaturenDB"
creatures_desc: "Name of creature"
creatures_url: "https://ilaris-online.de/app/kreaturen/{params}"

ilaris_help: "Posts an image of the given page if the argument is numeric. Else the database entry."
ilaris_desc: "Number or database entry (for example 4 or 'Duplicatus')"

card_help: "Posts an image of a specified rule card."
card_desc: "Name of rule card"
card_best_matches: "The three best matches are: {best}"

r_help: |
  Rolls dice.
  2d6+3: Sum the result of 2 6-sided dice and 3.
  2@3d20: Roll 3d20 and take the second highest i.e. (20,15,5) => 15.
  Special rolls:
  I: 1d20, Io: 1@2d20, Ioo 1@3d20
  III: 2@3d20, III': 2@4d20, III'' 2@5d20
r_desc: "Dice string to parse."
r_result: |
  ```md
  # {author} --- {identifier} {result}
  Details: {details}
  ```

group_prefix: "Your group (without username)"
group_name: "Name of your group."

gcreate_help: "Creates a new group with yourself as the GM."
gcreate_desc_default: "An exciting Ilaris session!"
gcreate_desc: "Description for your soon-to-be players"
gcreate_group: "Your group to create"
gcreate_time: "Time to play in GMT+1 (for example '24.02.24 14:00')"
gcreate_maxplayers: "Maximum number of players"
gcreate_channel_created: "Hey, <@{author}>! I created this channel for you and your group."
gcreate_group_exists: "You already have a group called {name}..."
gcreate_bad_args: >
  Pass at least the name of the group (in double quotes) to the command: 
  `!gcreate <group_name> [date=""]  [max_players=4] [description=""]`
  or use the form by pressing the button below.
gcreate_success: |
  ✅ New group created: **{group.name}**.
  Add channels: `!gaddchannel {group.slug} <channel_name>`. (GM only)
  Delete group: `!gdestroy {group.slug}` (GM only).
  Join as Players: `!gjoin {group.slug}`
submit_success: ":white_check_mark: Group created!"
name_ph: Group name
name_la: Name
date_ph: Date or time
date_la: Date
slots_la: Number of players
slots_ph: Maximum number of players
text_la: Description
text_ph: Group description

btn_join: Join
btn_edit: Edit
btn_destroy: Delete

glist_help: "Lists all joinable groups."
glist_desc: "'True' to show full groups, too"
glist_header: |
  These are all available groups.
  You can join them via button or using the `!gjoin` command. 
  If you have any difficulties, just ask. We will help where we can!
  _ _

group_info: |
  **{group.name}**
  {group.description}
  **Gamemaster:** <@{group.owner}>
  **Date:** {group.date}
  **Player:** {group.player_count}/{group.max_players}

gedit_help: "Bearbeitet eine Gruppe."
gedit_group_param: "Name der Gruppe, die bearbeitet werden soll."
gedit_key_param: "Field to change. Options are: 'name', 'date', 'max_players', 'description'"
gedit_val_param: "New value for the field"
gedit_key_error: "Invalid field. Valid fields are: 'name', 'date', 'max_players', 'description'"
gedit_success: "Group {group.name} changed."

gdestroy_help: "Destroys a group that you've created."
gdestroy_name_param: "Name of the group you want to destroy."
gdestroy_info: "Group {group.name} has been destroyed."
group_deleted_info: "{author.name} deleted the group {group.name}. You are not a member anymore."

gpurge_help: "Purges a group."
gpurge_group: "Group (full name)"

gsetdate_help: "Sets date."
gsetdate_value: "New date"

gsetnumberofplayers_help: "Sets the maximum number of players."
gsetnumberofplayers_value: "New number of players"

gsetdescription_help: "Sets description."
gsetdescription_group: "Your group (without username)"
gsetdescription_value: "New description"

gremove_help: "Removes a player from your group"
gremove_player: "Player to remove."
gremove_info: "Bye bye <@{player}>."

gjoin_help: "Join a group as a player"
gjoin_group: "Group you will join."
gjoin_info: "Greetings <@{player}>!"

gleave_help: "Leave a group as a player"
gleave_group: "Group you will leave."

gaddchannel_help: "Add a Channel for your group."
gaddchannel_channel: "Channel name to create"
gaddchannel_voice: "If True, a voice channel is created. Else a text channel."
gaddchannel_created_voice: "Created voice channel!"
gaddchannel_created_text: "Created text channel!"

# errors:
cmd_not_found: "Command not found. See `!help` for all commands."
bad_args: "Correct Usage: {pre}{cmd} {sig}"
unexpected_error: "Unexpected Error."
cmd_failed: "Command execution failed: {info}"
page_limit: "Ilaris only has 219 pages."
card_wrong_type: "Rule card has wrong file ending... Abort."
card_not_found: "No such rule card..."
join_own_group: "You can't join your own group."
not_found: "{name} not found..."
not_owner: "Sorry, that's only allowed for the owner of the group."
no_group_set: "No group could be assigned."